name: Create Release

on:
  push:
    # This workflow will run on any new tag that starts with 'v'
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This permission is required to create a release and upload assets
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload PDF to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            readme.pdf
